language: csharp
sudo: required
mono: none
dotnet: 2.2
dist: xenial
before_install:
  - bash scripts/install_protobuf.sh
  - nvm install node
  - npm install -g yarn
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - bash scripts/download_chakracore.sh 1_11_1
  - export LD_LIBRARY_PATH=$(pwd)/ChakraCoreFiles/lib/:$LD_LIBRARY_PATH
script:
  - bash scripts/build.sh
  - bash scripts/test.sh
after_script:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./results/coverage.opencover.xml" -t $CODECOV_TOKEN
deploy:
  - provider: script
    script: bash scripts/deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      tags: true
