version: 1.0.0.{build}
skip_tags: true
os: Windows Server 2012 R2
image: Visual Studio 2017
build:
  publish_nuget: true
  verbosity: minimal
configuration:
  - Debug
platform:
  - Any CPU
install:
  - choco install vcredist2017
  - ps: dotnet --info
  - ps: node --version
  - ps: (new-object net.webclient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-win64.zip', 'c:\protoc-3.7.0-win64.zip')
  - ps: (new-object net.webclient).DownloadFile('https://github.com/AElfProject/contract-plugin/releases/download/v1.0.1/contract_csharp_plugin-v1.0.1-win32.zip', 'c:\projects\aelf\scripts\contract_csharp_plugin-v1.0.1-win32.zip')
#  - cmd: dir c:\
  - cmd: unzip c:\protoc-3.7.0-win64.zip  -d c:\protoc\
  - cmd: set PATH=%PATH%;c:\protoc\bin\
  - cmd: unzip c:\projects\aelf\scripts\contract_csharp_plugin-v1.0.1-win32.zip -d c:\projects\aelf\scripts\

  
build_script:
#  - cmd: cd AElf.Contracts.Dividend\
#  - cmd: dir ..\protobuf\
#  - cmd: protoc --proto_path=..\protobuf --csharp_out=internal_access:.\Protobuf\Generated --csharp_opt=file_extension=.g.cs dpos_contract.proto
#  - cmd: protoc --proto_path=..\protobuf --csharp_out=.\Protobuf\Generated --csharp_opt=file_extension=.g.cs --contract_out=.\Protobuf\Generated dividend_contract.proto --plugin=protoc-gen-contract=..\scripts\contract_csharp_plugin.exe
#  - cmd: protoc --proto_path=..\protobuf --csharp_out=internal_access:.\Protobuf\Generated --csharp_opt=file_extension=.g.cs dpos_contract.proto && protoc --proto_path=..\protobuf --csharp_out=.\Protobuf\Generated --csharp_opt=file_extension=.g.cs --contract_out=.\Protobuf\Generated dividend_contract.proto --plugin=protoc-gen-contract=..\scripts\contract_csharp_plugin.exe
#  - cmd: cd ..
  - ps: dotnet build AElf.Console.sln
  - ps: dotnet build AElf.sln
  - ps: dotnet test AElf.sln
  - ps: dotnet build AElf.Management.sln
  - ps: dotnet test AElf.Management.sln
